version: '3.3'

volumes:
    mongodb_data:

services:  
    trade-shift-service:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
            -  MONGO_HOST=backend_mongo_1:29017
        ports:
            - 3000:3000
            
    mongo:
        image: mongo:4.0
        volumes: 
            - mongodb_data:/data/db
        command:  mongod --port 29017
        ports:
            - 29017:29017